### PR TITLE
Added php 8.0 support

### PR DESCRIPTION
**Pull request by JohnRoux**

### CODE REVIEW

**Comment by neolikotsi** [comment]
L7 and L8 guzzlehttp/guzzle is ^7.0.1. The package may fail in production. I have the package running L6 in my production apps, with no dependency errors.

**Comment by JohnRoux** [comment]
L6 you say :sweat_smile: 

I've got it running on a L8 project with PHP 7.4 which I've updated to 8.0
It's happy with this change for what it's worth :+1:

**Comment by JohnRoux** [comment]
If possible, a patch update to the tags would be appreciated :pray:

**Comment by neolikotsi** [comment]
Released 1.0.12 patch

**Pull request merged**
